### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by vrdriver** [capawesome-team/docker-ionic-capacitor-dev#1]
Hi, it's been a while since you've created or updated this. Is it still current, or need any other changes?
I'm just looking at implementing this kind of thing in to my dev workflow.
And, does this work for iOS apps too?
Cheers.
Steve

**Comment by robingenz** [comment]
This repository is currently not up to date. I will update it soon. iOS is not supported because you can't install the XCode build tools in Docker as far as I know.

**Comment by vrdriver** [comment]
Thanks Robin. Yeah, I'm looking for a new workflow to containerise my apps after node, ionic, capacitor versioning hell... so, I'm really keen to look in to this. It'll probably take me a while to figure it all, but you're listing seemed like a good start, so thanks. Once I get my head around it all with a working solution, I'll let you know.

**Comment by vrdriver** [comment]
Gosh. I just looked at the projects you work on... Seems like we do similar things...  I'm slightly surprised you haven't found a way as yet. Maybe paths be accessed in MacOS as a mounted network path from a Docker instance and compiled that way?
Anyway, just thinking outside the box. ta
